### PR TITLE
Handle shapeless recipes in redefinitions

### LINKED ISSUE #170: Crash on startup
After https://github.com/minetest-mods/moreblocks/commit/ddf8b39f5a7e47ab8aa2c09f26108d6edc573fad, mod crashes on startup:

```
2020-12-31 05:43:36: ERROR[Main]: ModError: Failed to load and run script from /var/lib/minetest/.minetest/worlds/world/worldmods/moreblocks/init.lua:
2020-12-31 05:43:36: ERROR[Main]: .../worlds/world/worldmods/moreblocks/redefinitions.lua:23: attempt to index field '?' (a nil value)
2020-12-31 05:43:36: ERROR[Main]: stack traceback:
2020-12-31 05:43:36: ERROR[Main]: 	.../worlds/world/worldmods/moreblocks/redefinitions.lua:23: in function 'reconstruct_internal_craft'
2020-12-31 05:43:36: ERROR[Main]: 	.../worlds/world/worldmods/moreblocks/redefinitions.lua:30: in function 'change_recipe_amount'
2020-12-31 05:43:36: ERROR[Main]: 	.../worlds/world/worldmods/moreblocks/redefinitions.lua:51: in function 'increase_craft_production'
2020-12-31 05:43:36: ERROR[Main]: 	.../worlds/world/worldmods/moreblocks/redefinitions.lua:68: in function 'increase_craft_production_table'
2020-12-31 05:43:36: ERROR[Main]: 	.../worlds/world/worldmods/moreblocks/redefinitions.lua:76: in main chunk
2020-12-31 05:43:36: ERROR[Main]: 	[C]: in function 'dofile'
2020-12-31 05:43:36: ERROR[Main]: 	....minetest/worlds/world/worldmods/moreblocks/init.lua:23: in main chunk
```

### PR DESCRIPTION
**Pull request by Oblomov**
They can be recognized from having width == 0, and don't need the items
list to be massaged to be transformed into the recipe field for the Lua
API.

Fixes #170.

### CODE REVIEW

File: redefinitions.lua [hunk 1]
```diff
@@ -17,28 +17,39 @@ local reconstruct_internal_craft = function(recipe)
...
+	if shapeless then
+		redo.type = "shapeless"
+	end
 	minetest.clear_craft(redo)
 
 	-- new output
 	redo.output = ("%s %d"):format(product, newamount)
+	-- preserve shapelessness
+	minetest.log(dump(recipe))
+	minetest.log(dump(redo))
```
Comment (OgelGames) [inline redefinitions.lua:52]: Shouldn't these have a log level, like `info` or `verbose`?

Comment (Oblomov) [reply redefinitions.lua]: Duh, forgot to remove the debug info. Force-pushed, thanks for spotting this.

**Comment by BuckarooBanzay** [comment]
@Calinou ping! :wink: this patch looks good, any chance it gets merged?

**Review by Calinou — APPROVED** [review]
