### PR TITLE
Fix strange placement behavior for non-default Stairs+ nodes

### LINKED ISSUE #167: slope placement with non-default nodes results in strange behavior
When i'm placing slope nodes from the `scifi_nodes` mod (github.com/D00Med/scifi_nodes/)
i get some weird placement issues:

screenshot_20201218_174631

Regardless of player position

Possbly related to: https://github.com/minetest-mods/moreblocks/pull/160

### PR DESCRIPTION
**Pull request by Oblomov**
Removing everything from the first underscore blows up when the mod name
has an underscore itself. Solve by extracting the category as the part
of the name that begins after the colon and ends at the first
underscore. As a bonus, this should make it easier to place nodes in the
same category even if they are from different mods.

This should fix #167

### CODE REVIEW

**Comment by Oblomov** [comment]
Luacheck is failing because of _ being unused? Somebody should fix luacheck 8-)

File: stairsplus/common.lua [hunk 1]
```diff
@@ -30,16 +30,27 @@ local wall_right_dirmap = {9, 18, 7, 12}
 local wall_left_dirmap = {11, 16, 5, 14}
 local ceil_dirmap = {20, 23, 22, 21}
 
+-- extract the stairsplus category from a node name
+-- assumes the name is in the form mod_name:category_original_ndoe_name
+local function name_to_category(name)
+	local colon, _ = name:find(":") or 0
```
Comment (Panquesito7) [inline stairsplus/common.lua:36]: Just remove this to fix LuaCheck.
```suggestion
	local colon = name:find(":") or 0
```

Comment (Oblomov) [reply stairsplus/common.lua:36]: I'll do but this is pretty stupid honestly, _ is the enstablished lua way to indicate an ignored parameter. Can luacheck be configured to take this into account?

Comment (Panquesito7) [reply stairsplus/common.lua]: You could do this instead:

```diff
- local colon, _ = name:find(":") or 0
+ local colon, _ = name:find(":") or 0 -- luacheck: ignore
```

Comment (Oblomov) [reply stairsplus/common.lua]: Thanks but I still think luacheck should be fixed, maybe I'll open a PR to fix that there ;-)

**Comment by BuckarooBanzay** [comment]
This fixed the issues from #167, thanks :+1:

File: CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,8 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ### Fixed
 
+- Fix category detection
+
```
Comment (Calinou) [inline CHANGELOG.md:13]:
```suggestion
- Fix strange placement behavior for non-default Stairs+ nodes.
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -9,6 +9,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ### Fixed
 
+- Fix strange placement behavior for non-default Stairs+ nodes.
```
Comment (Calinou) [inline CHANGELOG.md:12]:
```suggestion
- [Fixed strange placement behavior for non-default Stairs+ nodes.](https://github.com/minetest-mods/moreblocks/pull/168)
```

**Review by Calinou — APPROVED** [review]
Thanks!
